# QR methods: concrete example

$A$ will be a $m \times n$ matrix. We want to factor $A$ into $A=Q\begin{bmatrix}R \\ 0\end{bmatrix}$.

In this situation, $Q$ is an $m \times m$ orthogonal matrix. This means each column $j$ of $Q$ is a unit vector $\left(\left|\left| Q_{\ast,j} \right|\right|_2=1\right)$ and is at a right angle to any other column! $\left(\forall k\neq j: Q_{\ast,j}^T \cdot Q_{\ast,k} = 0\right)$.

$\begin{bmatrix}R \\ 0\end{bmatrix}$ is an $m \times n$ matrix where the last two rows are all 0's. $R$ is an $n \times n$ matrix representing the first n rows. $R$ is upper-triangular.

Thus, we transform the problem from approximating $x$ in $Ax\approx b$ to $Q\begin{bmatrix}R \\ 0\end{bmatrix}x\approx b$. But the nice property of $Q$ is that it's inverse is its transpose: $Q^TQ=I$. So we can multiply both sides by $Q^T$ on the left.

$$
Q^TQ\begin{bmatrix}R \\ 0\end{bmatrix}x\approx Q^Tb
$$

So that all we need to solve is the equation:

$$
\begin{bmatrix}R \\ 0\end{bmatrix}x\approx c
$$

Where $c=Q^Tb$, which we compute directly by multiplication.

Since $R$ (and $\begin{bmatrix}R \\ 0\end{bmatrix}$) is upper-triangular, we can use backwards subsitition to solve the first $m$ equations.

This is a system of $m$ equations with $n$ unknowns, just like our original system $Ax\approx b$, but since the last two rows are 0's, we can't solve them at all! In fact, the last $m-n$ equations look like:

$$0x_1+0x_2+0x_3+\cdots+0x_{n}=\mbox{some nonzero number}$$ 
$$0=\mbox{some nonzero number}$$ 

What's happened here is that the QR factorization has re-arranged our equation so that the top $n$ equations are "exactly" (except for rounding error) solvable, but the last $m-n$ equations can't be solved at all.

If we don't account for rounding error, our residual
is actually the same as the residual of just the last $m-n$ equations.

In [ ]:
import numpy as np
from copy import deepcopy

m = 5 # Number of equations
n = 3 # Number of unknowns

A = np.random.rand(m, n)
#A = np.array([[4, 9, -14], [3, 13, 2], [0, 5, 0]])
b = np.ones(m)
#b = np.ones(3)

print(f"A: {A.shape[0]}x{A.shape[1]}")
print(A)
print(f"b: {b.shape[0]} elements")
print(b)

A: 5x3
[[0.7515779  0.13628821 0.67433751]
 [0.83683455 0.41442425 0.2770372 ]
 [0.82558806 0.67541941 0.46522329]
 [0.9058038  0.74856777 0.31481558]
 [0.69145822 0.51812655 0.25473945]]
b: 5 elements
[1. 1. 1. 1. 1.]


In [ ]:
# DO NOT use this method in your Lab #3 solution!
Q, R0 = np.linalg.qr(A, mode='complete')

print(f"Q: {Q.shape[0]}x{Q.shape[1]}")
print(Q)
print(f"R0: {R0.shape[0]}x{R0.shape[1]}")
print(R0)

Q: 5x5
[[-0.41719884 -0.77489221  0.41204422  0.21458009  0.09829615]
 [-0.46452457 -0.25858892 -0.70992892 -0.32207726 -0.33108286]
 [-0.45828168  0.35803598  0.54952231 -0.50500586 -0.32370117]
 [-0.50280922  0.41012849 -0.08972745  0.74174252 -0.14402959]
 [-0.38382657  0.19046966 -0.12725842 -0.21215261  0.86901958]]
R0: 5x3
[[-1.80148607 -1.13415939 -0.87929467]
 [ 0.          0.43474662 -0.24997598]
 [ 0.          0.          0.27616539]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


Notice that that last two rows of $\begin{bmatrix}R \\ 0\end{bmatrix}$ are all 0's and that $R$ is upper-triangular!

We can also recover $A$ from $Q\begin{bmatrix}R \\ 0\end{bmatrix}$, but there's some rounding errors...

In [ ]:
print(Q.dot(R0)-A)

[[0.00000000e+00 2.49800181e-16 2.22044605e-16]
 [1.11022302e-16 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.11022302e-16 0.00000000e+00]
 [1.11022302e-16 1.11022302e-16 1.11022302e-16]
 [1.11022302e-16 1.11022302e-16 5.55111512e-17]]


Each column of Q is a unit vector! (Except for some roudning errors...)

In [ ]:
for j in range(m):
    print(f"column {j}: {np.linalg.norm(Q[:,j])}")

column 0: 1.0
column 1: 0.9999999999999999
column 2: 0.9999999999999998
column 3: 0.9999999999999999
column 4: 0.9999999999999999


$Q^TQ$ is the identity matrix! (Except for some rounding errors...)

In [ ]:
print(Q.T.dot(Q))

[[ 1.00000000e+00  8.77451787e-17 -5.00533066e-17 -4.36561964e-17
  -4.80504900e-17]
 [ 8.77451787e-17  1.00000000e+00 -1.37996118e-16 -2.16857135e-16
  -1.23839904e-16]
 [-5.00533066e-17 -1.37996118e-16  1.00000000e+00 -4.02344277e-16
  -2.05003046e-16]
 [-4.36561964e-17 -2.16857135e-16 -4.02344277e-16  1.00000000e+00
  -7.66247689e-17]
 [-4.80504900e-17 -1.23839904e-16 -2.05003046e-16 -7.66247689e-17
   1.00000000e+00]]


$Q^Tb$ (also known as $c=\begin{bmatrix}c_1 \\ c_2\end{bmatrix}$) doesn't have zeros in the last $m-n$ entries!

In [ ]:
c = Q.T.dot(b)
c1 = c[:n]
c2 = c[m-n+1:] # The +1 here accounts for the fact that numpy arrays start at 0!
print(c1, c2)

[-2.22664089 -0.07484699  0.03465174] [-0.08291312  0.16850211]


We expect the norm of our residual to be equal to the Euclidean norm of the last $m-n$ elements of $Q^Tb$ (also known as $c_2$):

In [ ]:
# Compute the expected residual from the QR factorization "c_2"
expected_r = np.linalg.norm(c2)
print(f"norm of the last {m-n} elements of c: {expected_r}")

norm of the last 2 elements of c: 0.18779655855961364


Is it?

In [ ]:
from scipy.optimize import lsq_linear
# DO NOT use this method in your Lab #3 solution!
x = lsq_linear(A, b).x
# compute the residual: r = Ax-b
r = np.linalg.norm(A.dot(x)-b)

print(r)

0.18779655855961364


Yep!